spring:
  application:
     name: empleados-db

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

server:
  port: 8888
